In [5]:
import pandas as pd
from pathlib import Path
current_dir = Path.cwd().parent
school_osslt = pd.read_csv(current_dir/"data"/"csv"/"2021_OSSLT.csv")
school_osslt

,School Name,Unnamed: 1,Unnamed: 2,Number of\nPreviously\nEligible\nStudents,Unnamed: 4,Unnamed: 5,Absent\n(All\nPreviously\nEligible\nStudents),Unnamed: 7,Unnamed: 8,Deferred\n(All\nPreviously\nEligible\nStudents),...,Unnamed: 14,Number of\nFully\nParticipating\nStudents,Unnamed: 16,Unnamed: 17,Successful\n(Fully\nParticipating),Unnamed: 19,Unnamed: 20,Not\nSuccessful\n(Fully\nParticipating),Unnamed: 22,Unnamed: 23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Province,NaN,NaN,148430,NaN,NaN,12%,NaN,NaN,...,NaN,NaN,127272,NaN,NaN,85%,NaN,NaN,15%,NaN
6,NaN,TDSB,NaN,NaN,17669,NaN,NaN,9%,NaN,NaN,...,NaN,NaN,15454,NaN,NaN,85%,NaN,NaN,15%,NaN
7,A Y Jackson Secondary School,NaN,NaN,312.0,NaN,NaN,8%,NaN,NaN,0%,...,NaN,286.0,NaN,NaN,88%,NaN,NaN,12%,NaN,NaN
8,Agincourt Collegiate Institute,NaN,NaN,388.0,NaN,NaN,1%,NaN,NaN,<1%,...,NaN,381.0,NaN,NaN,94%,NaN,NaN,6%,NaN,NaN
9,Albert Campbell Collegiate Institute,NaN,NaN,261.0,NaN,NaN,4%,NaN,NaN,7%,...,NaN,231.0,NaN,NaN,88%,NaN,NaN,12%,NaN,NaN
10,ALPHA II Alternative School (Sec),NaN,NaN,NaN,N/R1,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
11,Alternative Scarborough Education 1,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
12,Avondale Secondary Alternative School,NaN,NaN,19.0,NaN,NaN,16%,NaN,NaN,5%,...,NaN,15.0,NaN,NaN,73%,NaN,NaN,27%,NaN,NaN
13,Birchmount Park Collegiate Institute,NaN,NaN,169.0,NaN,NaN,22%,NaN,NaN,1%,...,NaN,128.0,NaN,NaN,79%,NaN,NaN,21%,NaN,NaN
14,Bloor Collegiate Institute,NaN,NaN,197.0,NaN,NaN,4%,NaN,NaN,0%,...,NaN,189.0,NaN,NaN,94%,NaN,NaN,6%,NaN,NaN
15,Burnhamthorpe Collegiate Institute,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
16,C W Jefferys Collegiate Institute,NaN,NaN,255.0,NaN,NaN,36%,NaN,NaN,0%,...,NaN,163.0,NaN,NaN,72%,NaN,NaN,28%,NaN,NaN
17,CALC Secondary School,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
18,Cedarbrae Collegiate Institute,NaN,NaN,264.0,NaN,NaN,13%,NaN,NaN,0%,...,NaN,226.0,NaN,NaN,76%,NaN,NaN,24%,NaN,NaN
19,Central Technical School,NaN,NaN,231.0,NaN,NaN,19%,NaN,NaN,0%,...,NaN,173.0,NaN,NaN,62%,NaN,NaN,38%,NaN,NaN
20,Central Toronto Academy,NaN,NaN,230.0,NaN,NaN,4%,NaN,NaN,<1%,...,NaN,202.0,NaN,NaN,86%,NaN,NaN,14%,NaN,NaN
21,City School,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
22,Contact Alternative School,NaN,NaN,12.0,NaN,NaN,8%,NaN,NaN,0%,...,NaN,11.0,NaN,NaN,36%,NaN,NaN,64%,NaN,NaN
23,Danforth Collegiate and Technical Institute,NaN,NaN,316.0,NaN,NaN,11%,NaN,NaN,0%,...,NaN,271.0,NaN,NaN,79%,NaN,NaN,21%,NaN,NaN
24,David and Mary Thomson Collegiate Institute,NaN,NaN,347.0,NaN,NaN,19%,NaN,NaN,0%,...,NaN,282.0,NaN,NaN,70%,NaN,NaN,30%,NaN,NaN
25,Delphi Secondary Alternative School,NaN,NaN,21.0,NaN,NaN,0%,NaN,NaN,10%,...,NaN,19.0,NaN,NaN,100%,NaN,NaN,0%,NaN,NaN
26,Don Mills Collegiate Institute,NaN,NaN,192.0,NaN,NaN,18%,NaN,NaN,0%,...,NaN,157.0,NaN,NaN,92%,NaN,NaN,8%,NaN,NaN

Now there are a lot of duplicates...

In [7]:
df_cleaned = school_osslt.dropna(how='all')
df_cleaned

,School Name,Unnamed: 1,Unnamed: 2,Number of\nPreviously\nEligible\nStudents,Unnamed: 4,Unnamed: 5,Absent\n(All\nPreviously\nEligible\nStudents),Unnamed: 7,Unnamed: 8,Deferred\n(All\nPreviously\nEligible\nStudents),...,Unnamed: 14,Number of\nFully\nParticipating\nStudents,Unnamed: 16,Unnamed: 17,Successful\n(Fully\nParticipating),Unnamed: 19,Unnamed: 20,Not\nSuccessful\n(Fully\nParticipating),Unnamed: 22,Unnamed: 23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Province,NaN,NaN,148430,NaN,NaN,12%,NaN,NaN,...,NaN,NaN,127272,NaN,NaN,85%,NaN,NaN,15%,NaN
6,NaN,TDSB,NaN,NaN,17669,NaN,NaN,9%,NaN,NaN,...,NaN,NaN,15454,NaN,NaN,85%,NaN,NaN,15%,NaN
7,A Y Jackson Secondary School,NaN,NaN,312.0,NaN,NaN,8%,NaN,NaN,0%,...,NaN,286.0,NaN,NaN,88%,NaN,NaN,12%,NaN,NaN
8,Agincourt Collegiate Institute,NaN,NaN,388.0,NaN,NaN,1%,NaN,NaN,<1%,...,NaN,381.0,NaN,NaN,94%,NaN,NaN,6%,NaN,NaN
9,Albert Campbell Collegiate Institute,NaN,NaN,261.0,NaN,NaN,4%,NaN,NaN,7%,...,NaN,231.0,NaN,NaN,88%,NaN,NaN,12%,NaN,NaN
10,ALPHA II Alternative School (Sec),NaN,NaN,NaN,N/R1,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
11,Alternative Scarborough Education 1,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
12,Avondale Secondary Alternative School,NaN,NaN,19.0,NaN,NaN,16%,NaN,NaN,5%,...,NaN,15.0,NaN,NaN,73%,NaN,NaN,27%,NaN,NaN
13,Birchmount Park Collegiate Institute,NaN,NaN,169.0,NaN,NaN,22%,NaN,NaN,1%,...,NaN,128.0,NaN,NaN,79%,NaN,NaN,21%,NaN,NaN
14,Bloor Collegiate Institute,NaN,NaN,197.0,NaN,NaN,4%,NaN,NaN,0%,...,NaN,189.0,NaN,NaN,94%,NaN,NaN,6%,NaN,NaN
15,Burnhamthorpe Collegiate Institute,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
16,C W Jefferys Collegiate Institute,NaN,NaN,255.0,NaN,NaN,36%,NaN,NaN,0%,...,NaN,163.0,NaN,NaN,72%,NaN,NaN,28%,NaN,NaN
17,CALC Secondary School,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
18,Cedarbrae Collegiate Institute,NaN,NaN,264.0,NaN,NaN,13%,NaN,NaN,0%,...,NaN,226.0,NaN,NaN,76%,NaN,NaN,24%,NaN,NaN
19,Central Technical School,NaN,NaN,231.0,NaN,NaN,19%,NaN,NaN,0%,...,NaN,173.0,NaN,NaN,62%,NaN,NaN,38%,NaN,NaN
20,Central Toronto Academy,NaN,NaN,230.0,NaN,NaN,4%,NaN,NaN,<1%,...,NaN,202.0,NaN,NaN,86%,NaN,NaN,14%,NaN,NaN
21,City School,NaN,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,...,NaN,NaN,N/R,NaN,NaN,N/R,NaN,NaN,N/R,NaN
22,Contact Alternative School,NaN,NaN,12.0,NaN,NaN,8%,NaN,NaN,0%,...,NaN,11.0,NaN,NaN,36%,NaN,NaN,64%,NaN,NaN
23,Danforth Collegiate and Technical Institute,NaN,NaN,316.0,NaN,NaN,11%,NaN,NaN,0%,...,NaN,271.0,NaN,NaN,79%,NaN,NaN,21%,NaN,NaN
24,David and Mary Thomson Collegiate Institute,NaN,NaN,347.0,NaN,NaN,19%,NaN,NaN,0%,...,NaN,282.0,NaN,NaN,70%,NaN,NaN,30%,NaN,NaN
25,Delphi Secondary Alternative School,NaN,NaN,21.0,NaN,NaN,0%,NaN,NaN,10%,...,NaN,19.0,NaN,NaN,100%,NaN,NaN,0%,NaN,NaN
26,Don Mills Collegiate Institute,NaN,NaN,192.0,NaN,NaN,18%,NaN,NaN,0%,...,NaN,157.0,NaN,NaN,92%,NaN,NaN,8%,NaN,NaN