In [2]:
import pandas as pd
from geopy.geocoders import Nominatim
from pathlib import Path
current_dir = Path.cwd().parent
schools_df_cleaned = pd.read_csv(current_dir/'school_data'/'combined_schools.csv')
geolocator = Nominatim(user_agent="CME538_project_email:laura.xu@mail.utoronto.ca")
schools_df_cleaned

,School Name_x,EQAO_Total # of\r\nStudents,EQAO_# of\r\nParticipating\r\nStudents,EQAO_# of\r\nStudents at\r\nLevels 3/4,EQAO_% at Levels\r\n3/4,OSSLT_Number of\r\nPreviously\r\nEligible\r\nStudents,OSSLT_Absent\r\n(All\r\nPreviously\r\nEligible\r\nStudents),OSSLT_Deferred\r\n(All\r\nPreviously\r\nEligible\r\nStudents),OSSLT_Successful\r\n(Fully\r\nParticipating),OSSLT_Not\r\nSuccessful\r\n(Fully\r\nParticipating),Partial Name_x,School Name_y,Score,Rank
0,A Y Jackson Secondary School,112,103,96,93%,312,8%,0%,88%,12%,a y jackson,a y jackson,7.9,77/689
1,Agincourt Collegiate Institute,184,172,125,73%,388,1%,<1%,94%,6%,agincourt,agincourt,8.3,41/689
2,Albert Campbell Collegiate Institute,169,158,100,63%,261,4%,7%,88%,12%,albert campbell,albert campbell,7.0,210/689
3,Birchmount Park Collegiate Institute,104,87,28,32%,169,22%,1%,79%,21%,birchmount park,birchmount park,5.2,496/689
4,Bloor Collegiate Institute,78,75,59,79%,197,4%,0%,94%,6%,bloor,bloor,8.5,26/689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Wexford Collegiate School for the Arts,118,107,45,42%,257,257,257,257,257,wexford collegiate-arts,wexford collegiate-arts,6.6,273/689
57,Winston Churchill Collegiate Institute,64,54,11,20%,173,173,173,173,173,winston churchill,winston churchill,3.4,628/689
58,Woburn Collegiate Institute,92,83,49,59%,247,247,247,247,247,woburn,woburn,6.9,227/689
59,York Memorial Collegiate Institute,67,63,21,33%,210,210,210,210,210,york memorial,york memorial,6.7,260/689
60,York Mills Collegiate Institute,174,159,113,71%,258,258,258,258,258,york mills,york mills,8.3,41/689

In [6]:
# Create a geolocator object
geolocator = Nominatim(user_agent="CME538_project_email:laura.xu@mail.utoronto.ca")

def get_lat_lon(address):
    location = geolocator.geocode(address)
    if location:
        return location.latitude, location.longitude
    else:
        return None, None

schools_df_cleaned[['latitude', 'longitude']] = schools_df_cleaned['School Name_x'].apply(lambda x: pd.Series(get_lat_lon(x)))

In [8]:
schools_df_cleaned.to_csv(current_dir/'school_data'/'combined_schools_with_cords.csv')